apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: python:alpine
        command: ["python"]
        args: ["-m", "http.server", "9376"]
        ports:
        - containerPort: 9376

