apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            value: "tentek-k8s"
          - name: POSTGRES_PASSWORD
            value: "tentek-k8s"