apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: postgres-daemonset
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "tentekds"
        - name: POSTGRES_PASSWORD
          value: "tentekds"
