apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rolebinding
  namespace: grafana
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: grafana
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io
