apiVersion: apps/v1
kind: Deployment
metadata:
 name: php-apache
 namespace: autoscale-php-apache
spec:
 selector:
   matchLabels:
     app: php-apache
 replicas: 1
 template:
   metadata:
     labels:
       app: php-apache
   spec:
     containers:
     - name: php-apache
       image: k8s.gcr.io/hpa-example
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 500m
           memory: 512Mi
         requests:
           cpu: 250m
           memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
 name: php-apache
 namespace: autoscale-php-apache
 labels:
   app: php-apache
spec:
 ports:
 - port: 80
 selector:
   app: php-apache
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: autoscale-php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50

