apiVersion: v1
kind: Service
metadata:
  name: http-service
  namespace: tentek
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

