apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: tentek
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: python:alpine
        command: ["/bin/sh", "-c"]
        args: ["echo 'Starting HTTP Server'; python -m http.server 8000"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: secret-volume
          mountPath: /secret
      volumes:
      - name: config-volume
        configMap:
          name: tentek-cm
      - name: secret-volume
        secret:
          secretName: tentek-secret
