apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "tentek"
        volumeMounts:
        - name: temp-storage
          mountPath: /var/lib/pgsql/data
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi"
      volumes:
      - name: temp-storage
        emptyDir: {}